package knowledgewrite

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"argos/internal/index"
	"argos/internal/knowledge"
	"argos/internal/registry"
)

func Design(root string, req DesignRequest) (DesignResponse, error) {
	reg, err := registry.Load(root)
	if err != nil {
		return DesignResponse{}, fmt.Errorf("load registry: %w", err)
	}
	official, err := knowledge.LoadOfficial(root)
	if err != nil {
		return DesignResponse{}, fmt.Errorf("load official knowledge: %w", err)
	}
	inbox, err := knowledge.LoadInbox(root)
	if err != nil {
		return DesignResponse{}, fmt.Errorf("load inbox knowledge: %w", err)
	}

	indexCapability := indexStatus(root)
	response := DesignResponse{
		Project: strings.TrimSpace(req.Project),
		Intent:  strings.TrimSpace(req.Intent),
		Capabilities: Capabilities{
			Filesystem: "enabled",
			Index:      indexCapability,
		},
		Registry: RegistryFacts{
			ProjectKnown:           projectKnown(reg, req.Project),
			TechDomains:            append([]string{}, reg.TechDomains...),
			BusinessDomains:        append([]string{}, reg.BusinessDomains...),
			projectTechDomains:     projectTechDomains(reg, req.Project),
			projectBusinessDomains: projectBusinessDomains(reg, req.Project),
		},
		ExistingKnowledge: ExistingMatches{
			Official: existingMatches("official", official, req),
			Inbox:    existingMatches("inbox", inbox, req),
		},
		DraftPathRisk: inspectDraftPathRisk(req.DraftPath),
		WritePolicy: WritePolicy{
			Write:         "after_design_review",
			OfficialWrite: "requires_explicit_review_path",
			Publish:       "requires_explicit_approval",
			PriorityMust:  "requires_explicit_approval",
			AISuggestions: "must_mark_assumptions",
		},
		NextSteps: []NextStep{
			{Step: "write_knowledge_design", Reason: "Review is required before draft knowledge writing."},
		},
	}
	if indexCapability == "enabled" {
		response.ExistingKnowledge.Index = indexExistingKnowledge(root, req)
	}
	response.KnowledgeDesignTemplate = buildKnowledgeDesignTemplate(response, req)
	response.WriteGuidance = buildWriteGuidance(response, req)
	return response, nil
}

func buildKnowledgeDesignTemplate(response DesignResponse, req DesignRequest) KnowledgeDesign {
	project := strings.TrimSpace(response.Project)
	if project == "" {
		project = "project"
	}
	intent := strings.TrimSpace(response.Intent)
	if intent == "" {
		intent = "Design reusable knowledge for future agents."
	}
	slug := slugForKnowledgeWrite(intent)
	draftPath := strings.TrimSpace(req.DraftPath)
	if draftPath == "" || pathRiskBlocksDraft(response.DraftPathRisk) {
		draftPath = defaultDraftPath(project, intent)
	} else {
		draftPath = filepath.ToSlash(filepath.Clean(draftPath))
	}
	overlapIDs := existingKnowledgeIDs(response.ExistingKnowledge.Official, response.ExistingKnowledge.Inbox, response.ExistingKnowledge.Index)
	pathRiskBlocks := pathRiskBlocksDraft(response.DraftPathRisk)
	missingContent := requestLooksMissingSubstantiveContent(req)
	designOnly := len(overlapIDs) > 0 || pathRiskBlocks || missingContent

	sources := Sources{
		UserInput:   []string{"User request: " + intent},
		AISuggested: []string{"Initial knowledge design generated by argos knowledge design."},
		Assumptions: []string{
			"The draft writer must replace template wording with reviewed, source-backed knowledge before publishing.",
		},
		Claims: []SourceClaim{
			{
				Claim:  "The user requested durable reusable knowledge for future agents.",
				Kind:   "fact",
				Trust:  "user_input",
				Source: []string{"knowledge design request intent"},
			},
			{
				Claim:          "The design template is AI-suggested guidance and requires review before durable use.",
				Kind:           "recommendation",
				Trust:          "ai_suggested",
				Source:         []string{"argos knowledge design"},
				RequiresReview: true,
			},
		},
	}
	if len(overlapIDs) > 0 {
		sources.Observed = []string{"knowledge design found existing related knowledge: " + strings.Join(overlapIDs, ", ")}
		sources.Claims = append(sources.Claims, SourceClaim{
			Claim:  "Existing related knowledge must be reviewed before draft writing.",
			Kind:   "fact",
			Trust:  "observed",
			Source: []string{"knowledge design existing knowledge"},
		})
	}
	if pathRiskBlocks {
		sources.Observed = append(sources.Observed, "knowledge design blocked draft path: "+draftPathRiskReviewReason(response.DraftPathRisk))
		sources.Claims = append(sources.Claims, SourceClaim{
			Claim:  "The supplied draft path requires review before draft writing.",
			Kind:   "fact",
			Trust:  "observed",
			Source: []string{"knowledge design draft path risk"},
		})
	}
	if missingContent {
		sources.Assumptions = []string{"The exact convention content was not provided in the design request."}
		sources.OpenQuestions = []string{"What exact convention should future agents preserve?"}
		sources.Claims = append(sources.Claims, SourceClaim{
			Claim:          "The exact actionable convention content is missing and must be reviewed before draft writing.",
			Kind:           "recommendation",
			Trust:          "ai_suggested",
			Source:         []string{"argos knowledge design"},
			RequiresReview: true,
		})
	}

	design := KnowledgeDesign{
		SchemaVersion: KnowledgeDesignSchemaVersion,
		UserRequest:   intent,
		KnowledgeGoal: "Design reusable knowledge for future agents: " + intent,
		Project:       project,
		Audience: Audience{
			Primary: "implementer_agent",
			AgentActionsSupported: []string{
				"find and apply reviewed knowledge during future development work",
				"respect source trust, applicability, and review boundaries",
			},
		},
		Scope: Scope{
			Projects:       []string{project},
			Stability:      "draft",
			Distribution:   "project",
			SubjectDomains: append([]string{}, response.Registry.projectBusinessDomains...),
			TechDomains:    append([]string{}, response.Registry.projectTechDomains...),
			FileGlobs:      []string{"**/*"},
			OutOfScope: []string{
				"official knowledge writing without explicit approval",
				"publishing without explicit approval",
				"priority must without explicit approval",
			},
		},
		Sources: sources,
		DraftOutput: DraftOutput{
			Kind:           "package",
			Type:           "package",
			Title:          titleFromIntent(intent),
			ID:             "package:" + project + "." + slug + ".v1",
			Path:           draftPath,
			Status:         "draft",
			Priority:       "should",
			Rationale:      "A package gives future agents one entrypoint plus room for references, examples, and checklists.",
			EntrypointLoad: "read_before_implementation",
			DraftState:     "draft",
		},
		FutureUse: FutureUse{
			TriggerRequests:  []string{intent},
			NegativeTriggers: []string{"Do not use outside the reviewed project scope or before resolving open review questions."},
			QueryPhrases:     []string{intent},
			ExpectedUse:      "Future agents should read this knowledge before implementing the matching task.",
			CitationPolicy:   "cite_after_use",
		},
		Applicability: Applicability{
			WhenToUse:    []string{"When future development work matches the reviewed knowledge goal."},
			WhenNotToUse: []string{"When the task is outside the reviewed scope or relies on unresolved assumptions."},
			Tradeoffs:    []string{"Draft knowledge improves reuse but must keep source trust and assumptions visible."},
		},
		ExistingKnowledge: ExistingKnowledgeDecision{
			OfficialMatches:      existingIDsFromMatches(response.ExistingKnowledge.Official),
			InboxMatches:         existingIDsFromMatches(response.ExistingKnowledge.Inbox),
			PossibleMatches:      existingIDsFromMatches(response.ExistingKnowledge.Index),
			Decision:             "create_new",
			Reason:               "No blocking existing knowledge was selected by the design template.",
			ReviewChoiceRequired: false,
		},
		WriteBoundary: WriteBoundary{
			Path:                        "inbox",
			WriteRequiresReviewApproval: true,
			ReviewPacketRequired:        true,
		},
		DraftFiles: []DraftFile{
			{
				Path:    filepath.ToSlash(filepath.Join(draftPath, "KNOWLEDGE.md")),
				Purpose: "package entrypoint",
				Load:    "read_before_implementation",
			},
		},
		CheckPlan: CheckPlan{
			ValidatePath: draftPath,
			FindabilityChecks: []FindabilityCheckScenario{
				{Project: project, Phase: strings.TrimSpace(req.Phase), Task: intent, Query: intent, Files: append([]string{}, req.Files...)},
			},
		},
		Review: Review{
			Questions: []string{
				"Is the proposed knowledge goal correct and specific enough?",
				"Are source trust, assumptions, and applicability boundaries accurate?",
			},
		},
	}

	if len(req.Files) > 0 {
		design.Scope.Files = append([]string{}, req.Files...)
	}
	if len(req.Domains) > 0 {
		techDomains, subjectDomains := classifyRequestDomains(req.Domains, response.Registry)
		design.Scope.TechDomains = uniqueNonEmpty(append(design.Scope.TechDomains, techDomains...))
		design.Scope.SubjectDomains = uniqueNonEmpty(append(design.Scope.SubjectDomains, subjectDomains...))
	}
	if strings.TrimSpace(req.Phase) != "" {
		design.FutureUse.Phases = []string{strings.TrimSpace(req.Phase)}
	}
	if strings.TrimSpace(req.FutureTask) != "" {
		design.FutureUse.TriggerRequests = append([]string{strings.TrimSpace(req.FutureTask)}, design.FutureUse.TriggerRequests...)
	}
	if strings.TrimSpace(req.Query) != "" {
		design.FutureUse.QueryPhrases = append([]string{strings.TrimSpace(req.Query)}, design.FutureUse.QueryPhrases...)
	}
	if requestLooksConsumerFacing(req) {
		design.Audience.Primary = "consumer_agent"
		design.Audience.AgentActionsSupported = []string{
			"help developers use or integrate with the documented project interface",
			"separate observed interface facts from user interpretation before advising consumers",
			"respect source trust, applicability, and review boundaries",
		}
	}
	if missingContent {
		design.Scope.Distribution = "personal"
		design.FutureUse.MissingNeeds = []string{"Exact convention content."}
		design.Review.Questions = []string{"What exact convention should future agents preserve?"}
	}
	if designOnly {
		design.DraftOutput.Kind = "review"
		design.DraftOutput.Type = "review"
		design.DraftOutput.ID = "review:" + project + "." + slug
		design.DraftOutput.Path = ""
		design.DraftOutput.Status = "review"
		design.DraftOutput.Priority = "may"
		design.DraftOutput.Rationale = designOnlyRationale(len(overlapIDs) > 0, pathRiskBlocks, missingContent)
		design.DraftOutput.EntrypointLoad = "reference_only"
		design.DraftOutput.DraftState = "design_only"
		design.ExistingKnowledge.Decision = "unresolved"
		design.ExistingKnowledge.Reason = designOnlyReason(overlapIDs, response.DraftPathRisk, pathRiskBlocks, missingContent)
		design.ExistingKnowledge.ReviewChoiceRequired = true
		design.DraftFiles = nil
		design.CheckPlan.ValidatePath = ""
		design.CheckPlan.FindabilityChecks = nil
		design.Review.DraftWriteApproved = false
		if len(overlapIDs) > 0 {
			design.Review.UnresolvedBlockers = append(design.Review.UnresolvedBlockers, "Choose create-new, update-existing, merge, or stop before draft writing.")
		}
		if pathRiskBlocks {
			design.Review.UnresolvedBlockers = append(design.Review.UnresolvedBlockers, "Provide an allowed inbox draft path before draft writing.")
		}
		if missingContent {
			design.Review.UnresolvedBlockers = append(design.Review.UnresolvedBlockers, "Provide the exact convention content before draft writing.")
		}
	}
	return design
}

func requestLooksConsumerFacing(req DesignRequest) bool {
	text := strings.ToLower(strings.Join(append([]string{
		req.Intent,
		req.FutureTask,
		req.Query,
	}, append(append([]string{}, req.Tags...), req.Files...)...), " "))
	if text == "" {
		return false
	}
	hasConsumerIntent := strings.Contains(text, "interface") ||
		strings.Contains(text, "interfaces") ||
		strings.Contains(text, "consumer") ||
		strings.Contains(text, "called by") ||
		strings.Contains(text, "callers") ||
		strings.Contains(text, "developers use") ||
		strings.Contains(text, "integrate") ||
		strings.Contains(text, "integration") ||
		strings.Contains(text, "business-capability") ||
		strings.Contains(text, "business points")
	hasSourceSignal := strings.Contains(text, "internal/api") ||
		strings.Contains(text, "api") ||
		strings.Contains(text, "consumer") ||
		strings.Contains(text, "interface")
	return hasConsumerIntent && hasSourceSignal
}

func requestLooksMissingSubstantiveContent(req DesignRequest) bool {
	text := strings.ToLower(strings.Join(append([]string{
		req.Intent,
		req.FutureTask,
		req.Query,
	}, append(append([]string{}, req.Tags...), req.Files...)...), " "))
	if text == "" {
		return false
	}
	hasConventionMarker := strings.Contains(text, "personal convention") ||
		strings.Contains(text, "project convention") ||
		strings.Contains(text, "project-convention")
	hasConventionIntent := hasConventionMarker || strings.Contains(text, "preserve it for future agents")
	if !hasConventionIntent || requestHasConcreteConventionDetails(text) {
		return false
	}
	hasVaguePersonalConvention := strings.Contains(text, "i have a personal convention") ||
		strings.Contains(text, "i have a project convention") ||
		strings.Contains(text, "my personal convention") ||
		strings.Contains(text, "my project convention")
	hasVagueConventionReference := hasConventionMarker &&
		(strings.Contains(text, "remember") || strings.Contains(text, "preserve it") || strings.Contains(text, "future agents"))
	hasGlobalTruthBoundary := strings.Contains(text, "without making it global truth")
	return hasVaguePersonalConvention || hasVagueConventionReference || hasGlobalTruthBoundary
}

func designPath(project string, intent string) string {
	project = strings.TrimSpace(project)
	if project == "" {
		project = "project"
	}
	return filepath.ToSlash(filepath.Join("knowledge/.inbox/designs", project, slugForKnowledgeWrite(intent), "design.json"))
}

func defaultDraftPath(project string, intent string) string {
	project = strings.TrimSpace(project)
	if project == "" {
		project = "project"
	}
	return filepath.ToSlash(filepath.Join("knowledge/.inbox/packages", project, slugForKnowledgeWrite(intent)))
}

func requestHasConcreteConventionDetails(text string) bool {
	for _, marker := range []string{"put", "use", "under", "path"} {
		if hasConcreteConventionMarker(text, marker) {
			return true
		}
	}
	return false
}

func hasConcreteConventionMarker(text string, marker string) bool {
	words := strings.FieldsFunc(text, func(r rune) bool {
		return r == ' ' || r == '-' || r == '_' || r == '/' || r == ':' || r == ',' || r == '.'
	})
	for i, word := range words {
		if word != marker || i+1 >= len(words) {
			continue
		}
		if !isVagueConventionPronoun(words[i+1]) {
			return true
		}
	}
	return false
}

func isVagueConventionPronoun(word string) bool {
	switch strings.ToLower(strings.TrimSpace(word)) {
	case "it", "this", "that", "them", "these", "those":
		return true
	default:
		return false
	}
}

func existingKnowledgeIDs(overlap ...[]ExistingMatch) []string {
	var ids []string
	for _, matches := range overlap {
		ids = append(ids, existingIDsFromMatches(matches)...)
	}
	return uniqueNonEmpty(ids)
}

func existingIDsFromMatches(matches []ExistingMatch) []string {
	var ids []string
	for _, match := range matches {
		ids = append(ids, strings.TrimSpace(match.ID))
	}
	return uniqueNonEmpty(ids)
}

func slugForKnowledgeWrite(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	var builder strings.Builder
	lastDash := false
	for _, r := range value {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			builder.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash && builder.Len() > 0 {
			builder.WriteByte('-')
			lastDash = true
		}
	}
	slug := strings.Trim(builder.String(), "-")
	if slug == "" {
		return "knowledge-design"
	}
	if len(slug) > 64 {
		slug = strings.Trim(slug[:64], "-")
	}
	if slug == "" {
		return "knowledge-design"
	}
	return slug
}

func titleFromIntent(intent string) string {
	intent = strings.TrimSpace(intent)
	if intent == "" {
		return "Knowledge Design Draft"
	}
	if len(intent) > 80 {
		intent = strings.TrimSpace(intent[:80])
	}
	return strings.TrimRight(intent, ".")
}

func projectKnown(reg registry.Registry, project string) bool {
	project = strings.TrimSpace(project)
	for _, candidate := range reg.Projects {
		if candidate.ID == project {
			return true
		}
	}
	return false
}

func projectTechDomains(reg registry.Registry, project string) []string {
	project = strings.TrimSpace(project)
	for _, candidate := range reg.Projects {
		if candidate.ID == project {
			return append([]string{}, candidate.TechDomains...)
		}
	}
	return nil
}

func projectBusinessDomains(reg registry.Registry, project string) []string {
	project = strings.TrimSpace(project)
	for _, candidate := range reg.Projects {
		if candidate.ID == project {
			return append([]string{}, candidate.BusinessDomains...)
		}
	}
	return nil
}

func classifyRequestDomains(domains []string, facts RegistryFacts) ([]string, []string) {
	var techDomains []string
	var subjectDomains []string
	for _, domain := range domains {
		domain = strings.TrimSpace(domain)
		if domain == "" {
			continue
		}
		if containsStringValue(facts.BusinessDomains, domain) {
			subjectDomains = append(subjectDomains, domain)
			continue
		}
		techDomains = append(techDomains, domain)
	}
	return uniqueNonEmpty(techDomains), uniqueNonEmpty(subjectDomains)
}

func indexStatus(root string) string {
	dbPath := filepath.Join(root, "argos", "index.db")
	info, err := os.Stat(dbPath)
	if err != nil || !info.Mode().IsRegular() {
		return "unavailable"
	}
	store, err := index.OpenReadOnly(dbPath)
	if err != nil {
		return "unavailable"
	}
	defer store.Close()
	if err := store.CheckSchema(); err != nil {
		return "unavailable"
	}
	return "enabled"
}

func inspectDraftPathRisk(path string) DraftPathRisk {
	path = strings.TrimSpace(path)
	if path == "" {
		return DraftPathRisk{Status: "not_checked"}
	}
	if filepath.IsAbs(path) {
		return DraftPathRisk{DraftPath: path, Status: "unsafe", Reason: "draft path must be relative"}
	}
	if hasParentSegment(path) {
		return DraftPathRisk{DraftPath: path, Status: "unsafe", Reason: "draft path must stay inside workspace"}
	}
	clean := filepath.Clean(path)
	slash := filepath.ToSlash(clean)
	if isInboxDraftPath(slash) {
		return DraftPathRisk{DraftPath: slash, Status: "allowed"}
	}
	if isOfficialDraftPath(slash) {
		return DraftPathRisk{DraftPath: slash, Status: "official_review_required", Reason: "official write requires explicit review path"}
	}
	return DraftPathRisk{DraftPath: slash, Status: "review-needed", Reason: "draft path is outside standard write inbox locations"}
}

func pathRiskBlocksDraft(risk DraftPathRisk) bool {
	switch risk.Status {
	case "", "not_checked", "allowed":
		return false
	default:
		return true
	}
}

func draftPathRiskReviewReason(risk DraftPathRisk) string {
	if risk.Reason == "" {
		return risk.Status
	}
	return risk.Status + ": " + risk.Reason
}

func hasParentSegment(path string) bool {
	for _, part := range strings.Split(filepath.ToSlash(path), "/") {
		if part == ".." {
			return true
		}
	}
	return false
}

func existingMatches(kind string, items []knowledge.Item, req DesignRequest) []ExistingMatch {
	terms := overlapTerms(req)
	var matches []ExistingMatch
	for _, item := range items {
		reasons := existingReasons(item, req, terms)
		if len(reasons) == 0 {
			continue
		}
		matches = append(matches, ExistingMatch{
			Kind:    kind,
			ID:      item.ID,
			Title:   item.Title,
			Path:    item.Path,
			Reasons: reasons,
		})
	}
	sortExisting(matches)
	return matches
}

func overlapTerms(req DesignRequest) []string {
	text := strings.ToLower(strings.Join([]string{req.Intent, req.FutureTask, req.Query}, " "))
	var terms []string
	for _, field := range strings.FieldsFunc(text, func(r rune) bool {
		return r == ' ' || r == '-' || r == '_' || r == '/' || r == ':' || r == ',' || r == '.'
	}) {
		field = strings.TrimSpace(field)
		if len(field) >= 4 && !isKnowledgeWriteOverlapStopword(field) {
			terms = append(terms, field)
		}
	}
	for _, tag := range req.Tags {
		terms = append(terms, strings.ToLower(tag))
	}
	return uniqueNonEmpty(terms)
}

func isKnowledgeWriteOverlapStopword(term string) bool {
	switch strings.ToLower(strings.TrimSpace(term)) {
	case "knowledge",
		"future",
		"agents",
		"agent",
		"project",
		"reusable",
		"create",
		"turn",
		"this",
		"other",
		"help",
		"understand",
		"into":
		return true
	default:
		return false
	}
}

func existingReasons(item knowledge.Item, req DesignRequest, terms []string) []string {
	if !existingKnowledgeProjectApplies(item, req.Project) {
		return nil
	}
	var contextReasons []string
	var relatedReasons []string
	project := strings.TrimSpace(req.Project)
	if containsStringValue(item.Projects, project) {
		contextReasons = append(contextReasons, "project:"+project)
	}
	for _, tag := range req.Tags {
		tag = strings.TrimSpace(tag)
		if containsStringValue(item.Tags, tag) {
			if isStrongExistingKnowledgeSignal(tag) {
				relatedReasons = append(relatedReasons, "tag:"+tag)
			} else {
				contextReasons = append(contextReasons, "tag:"+tag)
			}
		}
	}
	for _, domain := range req.Domains {
		domain = strings.TrimSpace(domain)
		if containsStringValue(item.TechDomains, domain) || containsStringValue(item.BusinessDomains, domain) {
			contextReasons = append(contextReasons, "domain:"+domain)
		}
	}
	searchText := strings.ToLower(strings.Join([]string{
		item.ID,
		item.Title,
		item.Path,
		strings.Join(item.Tags, " "),
		strings.Join(item.TechDomains, " "),
		strings.Join(item.BusinessDomains, " "),
		item.Body,
	}, " "))
	for _, term := range terms {
		if strings.Contains(searchText, strings.ToLower(term)) {
			if isStrongExistingKnowledgeSignal(term) {
				relatedReasons = append(relatedReasons, "term:"+term)
			} else {
				contextReasons = append(contextReasons, "term:"+term)
			}
		}
	}
	if len(relatedReasons) == 0 {
		return nil
	}
	reasons := append(contextReasons, relatedReasons...)
	return uniqueNonEmpty(reasons)
}

func existingKnowledgeProjectApplies(item knowledge.Item, project string) bool {
	project = strings.TrimSpace(project)
	if project == "" || len(item.Projects) == 0 {
		return true
	}
	return containsStringValue(item.Projects, project)
}

func isStrongExistingKnowledgeSignal(value string) bool {
	value = strings.ToLower(strings.TrimSpace(value))
	if value == "" || isKnowledgeWriteOverlapStopword(value) {
		return false
	}
	switch value {
	case "backend",
		"frontend",
		"database",
		"databases",
		"service",
		"services",
		"implementation",
		"implementing",
		"implement",
		"development",
		"work",
		"style",
		"styles",
		"standard",
		"standards",
		"best",
		"practice",
		"practices",
		"rule",
		"rules",
		"runbook",
		"runbooks",
		"checklist",
		"checklists",
		"contract",
		"contracts",
		"review",
		"reviews",
		"guidance",
		"document",
		"designed",
		"design",
		"capture",
		"write",
		"usage",
		"scenario",
		"topic":
		return false
	default:
		return true
	}
}

func indexExistingKnowledge(root string, req DesignRequest) []ExistingMatch {
	store, err := index.OpenReadOnly(filepath.Join(root, "argos", "index.db"))
	if err != nil {
		return nil
	}
	defer store.Close()
	if err := store.CheckSchema(); err != nil {
		return nil
	}
	matches, err := store.SearchText(strings.Join([]string{req.Intent, req.FutureTask, req.Query}, " "), 10)
	if err != nil {
		return nil
	}
	seen := map[string]bool{}
	terms := overlapTerms(req)
	var out []ExistingMatch
	for _, match := range matches {
		if seen[match.ItemID] {
			continue
		}
		seen[match.ItemID] = true
		item, err := store.GetItem(match.ItemID)
		if err != nil {
			continue
		}
		reasons := existingReasons(item, req, terms)
		if len(reasons) == 0 {
			continue
		}
		out = append(out, ExistingMatch{
			Kind:    "index",
			ID:      item.ID,
			Title:   item.Title,
			Path:    item.Path,
			Reasons: uniqueNonEmpty(append(reasons, "index_text_match")),
		})
	}
	sortExisting(out)
	return out
}

func sortExisting(matches []ExistingMatch) {
	sort.Slice(matches, func(i, j int) bool {
		if len(matches[i].Reasons) != len(matches[j].Reasons) {
			return len(matches[i].Reasons) > len(matches[j].Reasons)
		}
		return matches[i].ID < matches[j].ID
	})
}

func uniqueNonEmpty(values []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return out
}

func containsStringValue(values []string, want string) bool {
	if strings.TrimSpace(want) == "" {
		return false
	}
	for _, value := range values {
		if strings.EqualFold(strings.TrimSpace(value), want) {
			return true
		}
	}
	return false
}

func designOnlyRationale(hasOverlap bool, pathRiskBlocks bool, missingContent bool) string {
	switch {
	case hasOverlap && pathRiskBlocks && missingContent:
		return "Existing related knowledge, the supplied draft path, and missing convention content require review before draft writing."
	case hasOverlap && missingContent:
		return "Existing related knowledge and missing convention content require review before draft writing."
	case pathRiskBlocks && missingContent:
		return "The supplied draft path and missing convention content require review before draft writing."
	case missingContent:
		return "The exact convention content must be reviewed before draft writing."
	case hasOverlap && pathRiskBlocks:
		return "Existing related knowledge and the supplied draft path require review before draft writing."
	case pathRiskBlocks:
		return "The supplied draft path requires review before draft writing."
	default:
		return "Existing related knowledge requires a review decision before draft writing."
	}
}

func designOnlyReason(overlapIDs []string, risk DraftPathRisk, pathRiskBlocks bool, missingContent bool) string {
	hasOverlap := len(overlapIDs) > 0
	if hasOverlap {
		reason := "knowledge design found existing related knowledge: " + strings.Join(overlapIDs, ", ")
		if missingContent && pathRiskBlocks {
			return reason + "; blocked draft path: " + draftPathRiskReviewReason(risk) + "; exact convention content is missing"
		}
		if missingContent {
			return reason + "; exact convention content is missing"
		}
		if pathRiskBlocks {
			return reason + "; blocked draft path: " + draftPathRiskReviewReason(risk)
		}
		return reason
	}
	if missingContent && pathRiskBlocks {
		return "knowledge design blocked draft path: " + draftPathRiskReviewReason(risk) + "; exact convention content is missing"
	}
	if missingContent {
		return "knowledge design needs exact convention content before draft writing."
	}
	if pathRiskBlocks {
		return "knowledge design blocked draft path: " + draftPathRiskReviewReason(risk)
	}
	return "knowledge design requires review before draft writing."
}
